name: CMake

on:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
      - cmake_github_action
  pull_request:
    branches:
      - master
      - cmake_github_action

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # windows-latest or windows-2022 fail!?
    runs-on: windows-2019

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout submodules
      run: git submodule update --depth 1 --init --recursive

    - name: Configure CMake
      working-directory: ${{runner.workspace}}
      shell: bash
      # looks v141_xp Toolset requires VS 2019!: -T v141_xp
      run: cmake -G "Visual Studio 16 2019" -A Win32 -S ExtIO_RTL -B build_ExtIO_RTL

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build_ExtIO_RTL --config $BUILD_TYPE --target ExtIO_RTL

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cp "${{runner.workspace}}/ExtIO_RTL/README.md" ./
        cp "${{runner.workspace}}/ExtIO_RTL/COPYING" ./LICENSE
        cp "${{runner.workspace}}/build_ExtIO_RTL/Release/ExtIO_RTL.dll" ./

    - name: package and upload
      uses: actions/upload-artifact@v2
      with:
        name: extio_rtl
        path: |
            ${{runner.workspace}}/ExtIO_RTL.dll
            ${{runner.workspace}}/README.md
            ${{runner.workspace}}/LICENSE

